server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
  main:
    allow-circular-references: true

  datasource:
    jdbc-url: jdbc:log4jdbc:mariadb://58.225.23.7:3307/myasset?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=Asia/Seoul
    username: dba
    password: Dba3048!01
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

log4jdbc:
  drivers: org.mariadb.jdbc.Driver


## JWT Custom
jwt:
  secret:
    signature: "idlelife+opr"